// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsrreyvgrzgdsyjrbifn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcnJleXZncnpnZHN5anJiaWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NjYzOTksImV4cCI6MjA1NzA0MjM5OX0.CE5a9BT-n9wvQN8PHg6RmHE1tLfixkEHCtv3afe1jyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);